version: "3.9"
services:
  api:
    build: ./api
    container_name: incident-api
    image: incident-api
    volumes:
      - ./api:/app 
    restart: unless-stopped
    ports:
      - 8080:8080
  front:
    build: ./front
    container_name: incident-front
    image: incident-front
    volumes:
      - ./front:/app
    stdin_open: true
    ports:
      - 3000:3000