version: "3.9"
services:
  api:
    image: incident-api
    build: ./API
    ports:
      - 8080:8080
  front:
    build: ./front
    container_name: incident-front
    image: incident-front
    volumes:
      - ./front:/app
    stdin_open: true
    ports:
      - 3000:3000
